In [ ]:
import pandas as pd

In [44]:
years = ["2024"]
csv_numbers = [1, 2, 3]

rainfall_all = pd.DataFrame()

for year in years:
    for num in csv_numbers:
        base_path = f"Resources/weather_data/rainfall/{year}/data ({num}).csv" 

        header_row = pd.read_csv(base_path, nrows=0).columns[0]
        rainfall_data = pd.read_csv(base_path, skiprows=4)

        county_date = header_row.split()
        rainfall_month = county_date[0]
        rainfall_year = county_date[1]

        rainfall_data["Month"] = rainfall_month
        rainfall_data["Year"] = rainfall_year
        rainfall_all = pd.concat([rainfall_all, rainfall_data], ignore_index=True)

        
rainfall_all

,ID,Name,State,Value,Anomaly (1901-2000 base period),Rank,1901-2000 Mean,Month,Year
0,CA-001,Alameda County,California,3.44,0.57,89,2.87,March,2024
1,CA-003,Alpine County,California,9.02,3.92,111,5.10,March,2024
2,CA-005,Amador County,California,6.46,0.85,87,5.61,March,2024
3,CA-007,Butte County,California,6.45,0.12,79,6.34,March,2024
4,CA-009,Calaveras County,California,6.52,0.94,89,5.58,March,2024
...,...,...,...,...,...,...,...,...,...
169,CA-107,Tulare County,California,2.93,-1.19,56,4.12,January,2024
170,CA-109,Tuolumne County,California,5.94,-1.74,61,7.68,January,2024
171,CA-111,Ventura County,California,2.57,-1.87,56,4.44,January,2024
172,CA-113,Yolo County,California,3.94,-0.31,71,4.25,January,2024
173,CA-115,Yuba County,California,8.06,0.63,84,7.43,January,2024